# Generated by Django 4.1 on 2022-11-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_post_app.blogpost')),
            ],
        ),
    ]
