# Generated by Django 4.1 on 2022-11-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0002_blogpostcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_post_app.blogpost'),
        ),
    ]
