# Generated by Django 4.1 on 2022-11-09 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_post_app', '0003_alter_blogpostcomments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpostcomments',
            old_name='comment',
            new_name='body',
        ),
        migrations.AddField(
            model_name='blogpostcomments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpostcomments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogpostcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_post_app.blogpost'),
        ),
    ]
