# Generated by Django 4.1 on 2022-11-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account'),
        ('blog_post_app', '0007_alter_blognotallowedto_blog_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='not_allowed_for',
            field=models.ManyToManyField(to='user.account'),
        ),
    ]
