# Generated by Django 3.2 on 2022-11-14 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_post_app', '0008_blogpost_not_allowed_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blognotallowedto',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='not_allowed_for',
        ),
        migrations.AddField(
            model_name='blognotallowedto',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_post_app.blogpost'),
        ),
        migrations.RemoveField(
            model_name='blognotallowedto',
            name='user',
        ),
        migrations.AddField(
            model_name='blognotallowedto',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
