# Generated by Django 3.2 on 2022-11-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post_app', '0012_auto_20221123_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='text',
            field=models.TextField(),
        ),
    ]
