# Generated by Django 4.1 on 2022-10-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NavbarChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_child_name', models.CharField(max_length=100)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.navbar')),
            ],
        ),
    ]
