# Generated by Django 3.2 on 2022-11-14 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_viewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
