# Generated by Django 3.2 on 2022-11-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_auto_20221123_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='name_teacher',
            new_name='account_name',
        ),
    ]
