# Generated by Django 3.2 on 2022-11-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
