# Generated by Django 3.2 on 2022-11-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20221123_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_users',
            field=models.ManyToManyField(null=True, related_name='users_allowed', to='user.Account'),
        ),
    ]
