# Generated by Django 3.2 on 2022-11-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20221123_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='user.Account'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_users', to='user.Account'),
        ),
    ]
