# Generated by Django 3.2 on 2022-11-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_user_reset_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_code',
        ),
    ]
